-- Script generated by Manus AI

local Players = game:GetService("Players")
local LocalPlayer = Players.LocalPlayer
local PlayerGui = LocalPlayer:WaitForChild("PlayerGui")

local ScreenGui = Instance.new("ScreenGui")
ScreenGui.Name = "GrowAGardenScriptUI"
ScreenGui.Parent = PlayerGui

local MainFrame = Instance.new("Frame")
MainFrame.Name = "MainFrame"
MainFrame.Size = UDim2.new(0.8, 0, 0.8, 0) -- 80% of screen size
MainFrame.Position = UDim2.new(0.1, 0, 0.1, 0) -- Centered
MainFrame.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
MainFrame.BorderSizePixel = 0
MainFrame.Draggable = true -- Make the UI draggable
MainFrame.Parent = ScreenGui

local Corner = Instance.new("UICorner")
Corner.CornerRadius = UDim.new(0, 10)
Corner.Parent = MainFrame

local UIListLayout = Instance.new("UIListLayout")
UIListLayout.FillDirection = Enum.FillDirection.Horizontal
UIListLayout.HorizontalAlignment = Enum.HorizontalAlignment.Left
UIListLayout.VerticalAlignment = Enum.VerticalAlignment.Top
UIListLayout.Padding = UDim.new(0, 10)
UIListLayout.Parent = MainFrame

local TitleBar = Instance.new("Frame")
TitleBar.Name = "TitleBar"
TitleBar.Size = UDim2.new(1, 0, 0.08, 0) -- 8% of frame height
TitleBar.Position = UDim2.new(0, 0, 0, 0)
TitleBar.BackgroundColor3 = Color3.fromRGB(60, 60, 60)
TitleBar.BorderSizePixel = 0
TitleBar.Parent = MainFrame

local TitleLabel = Instance.new("TextLabel")
TitleLabel.Name = "TitleLabel"
TitleLabel.Size = UDim2.new(1, 0, 1, 0)
TitleLabel.Position = UDim2.new(0, 0, 0, 0)
TitleLabel.BackgroundTransparency = 1
TitleLabel.Text = "Grow a Garden Script"
TitleLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
TitleLabel.Font = Enum.Font.GothamBold
TitleLabel.TextSize = 24
TitleLabel.TextScaled = true
TitleLabel.Parent = TitleBar

local CloseButton = Instance.new("TextButton")
CloseButton.Name = "CloseButton"
CloseButton.Size = UDim2.new(0.05, 0, 1, 0)
CloseButton.Position = UDim2.new(0.95, 0, 0, 0)
CloseButton.BackgroundColor3 = Color3.fromRGB(200, 0, 0)
CloseButton.Text = "X"
CloseButton.TextColor3 = Color3.fromRGB(255, 255, 255)
CloseButton.Font = Enum.Font.GothamBold
CloseButton.TextSize = 20
CloseButton.Parent = TitleBar

CloseButton.MouseButton1Click:Connect(function()
    ScreenGui:Destroy()
end)

-- Left Panel for Menu
local MenuPanel = Instance.new("Frame")
MenuPanel.Name = "MenuPanel"
MenuPanel.Size = UDim2.new(0.25, 0, 0.92, 0) -- 25% width, remaining height
MenuPanel.Position = UDim2.new(0, 0, 0.08, 0)
MenuPanel.BackgroundColor3 = Color3.fromRGB(50, 50, 50)
MenuPanel.BorderSizePixel = 0
MenuPanel.Parent = MainFrame

local MenuListLayout = Instance.new("UIListLayout")
MenuListLayout.FillDirection = Enum.FillDirection.Vertical
MenuListLayout.HorizontalAlignment = Enum.HorizontalAlignment.Center
MenuListLayout.VerticalAlignment = Enum.VerticalAlignment.Top
MenuListLayout.Padding = UDim.new(0, 5)
MenuListLayout.Parent = MenuPanel

-- Right Panel for Content
local ContentPanel = Instance.new("Frame")
ContentPanel.Name = "ContentPanel"
ContentPanel.Size = UDim2.new(0.75, 0, 0.92, 0) -- 75% width, remaining height
ContentPanel.Position = UDim2.new(0.25, 0, 0.08, 0)
ContentPanel.BackgroundColor3 = Color3.fromRGB(70, 70, 70)
ContentPanel.BorderSizePixel = 0
ContentPanel.Parent = MainFrame

local ContentListLayout = Instance.new("UIListLayout")
ContentListLayout.FillDirection = Enum.FillDirection.Vertical
ContentListLayout.HorizontalAlignment = Enum.HorizontalAlignment.Left
ContentListLayout.VerticalAlignment = Enum.VerticalAlignment.Top
ContentListLayout.Padding = UDim.new(0, 10)
ContentListLayout.Parent = ContentPanel

-- Function to create a menu button
local function createMenuButton(name)
    local Button = Instance.new("TextButton")
    Button.Name = name .. "Button"
    Button.Size = UDim2.new(0.9, 0, 0.1, 0)
    Button.BackgroundColor3 = Color3.fromRGB(80, 80, 80)
    Button.Text = name
    Button.TextColor3 = Color3.fromRGB(255, 255, 255)
    Button.Font = Enum.Font.GothamBold
    Button.TextSize = 18
    Button.Parent = MenuPanel

    local ButtonCorner = Instance.new("UICorner")
    ButtonCorner.CornerRadius = UDim.new(0, 5)
    ButtonCorner.Parent = Button

    return Button
end

-- Add menu buttons (will be populated in next phases)
local CharacterButton = createMenuButton("Character")
local SeedButton = createMenuButton("Seed")
local GearButton = createMenuButton("Gear")
local PetButton = createMenuButton("Pet")

-- Hide all content frames initially
local function hideAllContentFrames()
    for _, child in ipairs(ContentPanel:GetChildren()) do
        if child:IsA("Frame") and child.Name:match("ContentFrame$") then
            child.Visible = false
        end
    end
end

-- Character Content Frame
local CharacterContentFrame = Instance.new("Frame")
CharacterContentFrame.Name = "CharacterContentFrame"
CharacterContentFrame.Size = UDim2.new(1, 0, 1, 0)
CharacterContentFrame.BackgroundTransparency = 1
CharacterContentFrame.Parent = ContentPanel
CharacterContentFrame.Visible = false

-- Seed Content Frame
local SeedContentFrame = Instance.new("Frame")
SeedContentFrame.Name = "SeedContentFrame"
SeedContentFrame.Size = UDim2.new(1, 0, 1, 0)
SeedContentFrame.BackgroundTransparency = 1
SeedContentFrame.Parent = ContentPanel
SeedContentFrame.Visible = false

-- Gear Content Frame
local GearContentFrame = Instance.new("Frame")
GearContentFrame.Name = "GearContentFrame"
GearContentFrame.Size = UDim2.new(1, 0, 1, 0)
GearContentFrame.BackgroundTransparency = 1
GearContentFrame.Parent = ContentPanel
GearContentFrame.Visible = false

-- Pet Content Frame
local PetContentFrame = Instance.new("Frame")
PetContentFrame.Name = "PetContentFrame"
PetContentFrame.Size = UDim2.new(1, 0, 1, 0)
PetContentFrame.BackgroundTransparency = 1
PetContentFrame.Parent = ContentPanel
PetContentFrame.Visible = false

-- Connect menu buttons to show/hide content frames
CharacterButton.MouseButton1Click:Connect(function()
    hideAllContentFrames()
    CharacterContentFrame.Visible = true
end)

SeedButton.MouseButton1Click:Connect(function()
    hideAllContentFrames()
    SeedContentFrame.Visible = true
end)

GearButton.MouseButton1Click:Connect(function()
    hideAllContentFrames()
    GearContentFrame.Visible = true
end)

PetButton.MouseButton1Click:Connect(function()
    hideAllContentFrames()
    PetContentFrame.Visible = true
end)

-- Initially show Character tab
hideAllContentFrames()
CharacterContentFrame.Visible = true

-- Make the MainFrame draggable
local dragging
local dragInput
local dragStart
local startPos

MainFrame.InputBegan:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
        dragging = true
        dragInput = input
        dragStart = input.Position
        startPos = MainFrame.Position

        input.Changed:Connect(function()
            if input.UserInputState == Enum.UserInputState.Ended then
                dragging = false
            end
        end)
    end
end)

MainFrame.InputChanged:Connect(function(input)
    if input == dragInput and dragging then
        local delta = input.Position - dragStart
        MainFrame.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
    end
end)

-- Placeholder for Character speed control (will be implemented in next phase)
local SpeedLabel = Instance.new("TextLabel")
SpeedLabel.Name = "SpeedLabel"
SpeedLabel.Size = UDim2.new(0.3, 0, 0.1, 0)
SpeedLabel.Position = UDim2.new(0.05, 0, 0.1, 0)
SpeedLabel.BackgroundTransparency = 1
SpeedLabel.Text = "Player Speed:"
SpeedLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
SpeedLabel.Font = Enum.Font.Gotham
SpeedLabel.TextSize = 18
SpeedLabel.TextXAlignment = Enum.TextXAlignment.Left
SpeedLabel.Parent = CharacterContentFrame

local SpeedTextBox = Instance.new("TextBox")
SpeedTextBox.Name = "SpeedTextBox"
SpeedTextBox.Size = UDim2.new(0.2, 0, 0.08, 0)
SpeedTextBox.Position = UDim2.new(0.35, 0, 0.1, 0)
SpeedTextBox.PlaceholderText = "Enter speed"
SpeedTextBox.Text = "16" -- Default speed
SpeedTextBox.TextColor3 = Color3.fromRGB(255, 255, 255)
SpeedTextBox.BackgroundColor3 = Color3.fromRGB(90, 90, 90)
SpeedTextBox.Font = Enum.Font.Gotham
SpeedTextBox.TextSize = 16
SpeedTextBox.Parent = CharacterContentFrame

local SpeedToggleButton = Instance.new("TextButton")
SpeedToggleButton.Name = "SpeedToggleButton"
SpeedToggleButton.Size = UDim2.new(0.1, 0, 0.08, 0)
SpeedToggleButton.Position = UDim2.new(0.58, 0, 0.1, 0)
SpeedToggleButton.BackgroundColor3 = Color3.fromRGB(0, 150, 0) -- Green for active
SpeedToggleButton.Text = "✔"
SpeedToggleButton.TextColor3 = Color3.fromRGB(255, 255, 255)
SpeedToggleButton.Font = Enum.Font.GothamBold
SpeedToggleButton.TextSize = 20
SpeedToggleButton.Parent = CharacterContentFrame

local speedEnabled = false
local originalWalkSpeed = LocalPlayer.Character and LocalPlayer.Character.Humanoid.WalkSpeed or 16

SpeedToggleButton.MouseButton1Click:Connect(function()
    speedEnabled = not speedEnabled
    if speedEnabled then
        SpeedToggleButton.BackgroundColor3 = Color3.fromRGB(0, 150, 0)
        SpeedToggleButton.Text = "✔"
        local newSpeed = tonumber(SpeedTextBox.Text)
        if newSpeed then
            if LocalPlayer.Character and LocalPlayer.Character.Humanoid then
                LocalPlayer.Character.Humanoid.WalkSpeed = newSpeed
            end
        end
    else
        SpeedToggleButton.BackgroundColor3 = Color3.fromRGB(150, 0, 0)
        SpeedToggleButton.Text = "✖"
        if LocalPlayer.Character and LocalPlayer.Character.Humanoid then
            LocalPlayer.Character.Humanoid.WalkSpeed = originalWalkSpeed
        end
    end
end)

SpeedTextBox.FocusLost:Connect(function(enterPressed)
    if enterPressed then
        local newSpeed = tonumber(SpeedTextBox.Text)
        if newSpeed and speedEnabled then
            if LocalPlayer.Character and LocalPlayer.Character.Humanoid then
                LocalPlayer.Character.Humanoid.WalkSpeed = newSpeed
            end
        end
    end
end)

-- Initial state for speed toggle
SpeedToggleButton.BackgroundColor3 = Color3.fromRGB(150, 0, 0)
SpeedToggleButton.Text = "✖"

-- Placeholder for Seed items (will be implemented in next phase)
local SeedItemsLayout = Instance.new("UIListLayout")
SeedItemsLayout.FillDirection = Enum.FillDirection.Vertical
SeedItemsLayout.HorizontalAlignment = Enum.HorizontalAlignment.Left
SeedItemsLayout.VerticalAlignment = Enum.VerticalAlignment.Top
SeedItemsLayout.Padding = UDim.new(0, 5)
SeedItemsLayout.Parent = SeedContentFrame

-- Placeholder for Gear items (will be implemented in next phase)
local GearItemsLayout = Instance.new("UIListLayout")
GearItemsLayout.FillDirection = Enum.FillDirection.Vertical
GearItemsLayout.HorizontalAlignment = Enum.HorizontalAlignment.Left
GearItemsLayout.VerticalAlignment = Enum.VerticalAlignment.Top
GearItemsLayout.Padding = UDim.new(0, 5)
GearItemsLayout.Parent = GearContentFrame

-- Placeholder for Pet items (will be implemented in next phase)
local PetItemsLayout = Instance.new("UIListLayout")
PetItemsLayout.FillDirection = Enum.FillDirection.Vertical
PetItemsLayout.HorizontalAlignment = Enum.HorizontalAlignment.Left
PetItemsLayout.VerticalAlignment = Enum.VerticalAlignment.Top
PetItemsLayout.Padding = UDim.new(0, 5)
PetItemsLayout.Parent = PetContentFrame

-- Function to create a toggle button with icon (for Seeds, Gear, Pets)
local function createToggleItem(parentFrame, itemName, scriptCode)
    local ItemFrame = Instance.new("Frame")
    ItemFrame.Name = itemName .. "Frame"
    ItemFrame.Size = UDim2.new(1, 0, 0.08, 0)
    ItemFrame.BackgroundTransparency = 1
    ItemFrame.Parent = parentFrame

    local ItemLabel = Instance.new("TextLabel")
    ItemLabel.Name = "ItemLabel"
    ItemLabel.Size = UDim2.new(0.7, 0, 1, 0)
    ItemLabel.Position = UDim2.new(0, 0, 0, 0)
    ItemLabel.BackgroundTransparency = 1
    ItemLabel.Text = itemName
    ItemLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
    ItemLabel.Font = Enum.Font.Gotham
    ItemLabel.TextSize = 16
    ItemLabel.TextXAlignment = Enum.TextXAlignment.Left
    ItemLabel.Parent = ItemFrame

    local ToggleButton = Instance.new("TextButton")
    ToggleButton.Name = "ToggleButton"
    ToggleButton.Size = UDim2.new(0.1, 0, 0.8, 0)
    ToggleButton.Position = UDim2.new(0.8, 0, 0.1, 0)
    ToggleButton.BackgroundColor3 = Color3.fromRGB(150, 0, 0) -- Red for inactive
    ToggleButton.Text = "✖"
    ToggleButton.TextColor3 = Color3.fromRGB(255, 255, 255)
    ToggleButton.Font = Enum.Font.GothamBold
    ToggleButton.TextSize = 20
    ToggleButton.Parent = ItemFrame

    local active = false
    local connection = nil

    ToggleButton.MouseButton1Click:Connect(function()
        active = not active
        if active then
            ToggleButton.BackgroundColor3 = Color3.fromRGB(0, 150, 0)
            ToggleButton.Text = "✔"
            -- Execute the script code in a loop
            connection = game:GetService("RunService").Heartbeat:Connect(function()
                local success, err = pcall(function()
                    loadstring(scriptCode)()
                end)
                if not success then
                    warn("Error executing script for " .. itemName .. ": " .. err)
                end
            end)
        else
            ToggleButton.BackgroundColor3 = Color3.fromRGB(150, 0, 0)
            ToggleButton.Text = "✖"
            if connection then
                connection:Disconnect()
                connection = nil
            end
        end
    end)
end)

-- Seeds List - All available seeds in Grow a Garden
local seedsList = {
    -- Common Seeds
    "Carrot", "Strawberry", "Blueberry", "Tomato", "Cauliflower", "Watermelon", "Apple", "Orange", "Grape", "Lemon",
    "Corn", "Potato", "Onion", "Lettuce", "Cabbage", "Broccoli", "Spinach", "Radish", "Beet", "Turnip",
    
    -- Uncommon Seeds
    "Avocado", "Peach", "Coconut", "Pineapple", "Banana", "Kiwi", "Mango", "Papaya", "Passionfruit", "Dragon Fruit",
    "Bell Pepper", "Prickly Pear", "Cherry", "Plum", "Apricot", "Nectarine", "Pomegranate", "Fig", "Date", "Olive",
    
    -- Rare Seeds
    "Cactus", "Bamboo", "Rose", "Tulip", "Sunflower", "Lily", "Orchid", "Jasmine", "Lavender", "Mint",
    "Basil", "Rosemary", "Thyme", "Sage", "Parsley", "Cilantro", "Dill", "Chives", "Oregano", "Tarragon",
    
    -- Epic Seeds
    "Mushroom", "Truffle", "Ginseng", "Aloe Vera", "Eucalyptus", "Tea Plant", "Coffee Bean", "Vanilla", "Cinnamon", "Cardamom",
    "Saffron", "Black Pepper", "Nutmeg", "Clove", "Star Anise", "Bay Leaf", "Fennel", "Cumin", "Coriander", "Turmeric",
    
    -- Legendary Seeds
    "Golden Apple", "Silver Grape", "Crystal Berry", "Diamond Fruit", "Ruby Cherry", "Emerald Lime", "Sapphire Plum", "Topaz Orange",
    "Amethyst Grape", "Opal Peach", "Platinum Pear", "Titanium Tomato", "Copper Carrot", "Bronze Beet", "Iron Onion",
    
    -- Mythical Seeds
    "Phoenix Fruit", "Dragon Berry", "Unicorn Apple", "Griffin Grape", "Pegasus Peach", "Kraken Kelp", "Mermaid Mint", "Fairy Flower",
    "Angel Wing", "Demon Thorn", "Spirit Blossom", "Ghost Pepper", "Vampire Vine", "Werewolf Wheat", "Zombie Zucchini",
    
    -- Divine Seeds
    "God Fruit", "Heaven Berry", "Divine Apple", "Sacred Grape", "Holy Peach", "Blessed Berry", "Miracle Mint", "Celestial Cherry",
    "Eternal Flower", "Infinite Fruit", "Cosmic Berry", "Stellar Apple", "Galactic Grape", "Universal Peach", "Quantum Berry",
    
    -- Event/Special Seeds
    "Cherry Blossom", "Durian", "Cranberry", "Lotus", "Eggplant", "Venus Flytrap", "Blood Orange", "Black Rose", "Blue Tulip",
    "Purple Grape", "Golden Rose", "Silver Lily", "Crystal Flower", "Rainbow Berry", "Sunset Fruit", "Moonlight Berry",
    
    -- Summer Update Seeds
    "Elephant Ears", "Honeysuckle", "Hinomai", "Firefly Fruit", "Summer Berry", "Tropical Mango", "Beach Coconut", "Island Pineapple",
    "Ocean Berry", "Coral Fruit", "Seashell Berry", "Starfish Fruit", "Dolphin Berry", "Whale Fruit", "Shark Berry",
    
    -- Zen Update Seeds
    "Zen Berry", "Meditation Mint", "Peace Lily", "Harmony Fruit", "Balance Berry", "Tranquil Tulip", "Serene Sunflower", "Calm Cherry",
    "Quiet Berry", "Silent Fruit", "Peaceful Peach", "Gentle Grape", "Soft Berry", "Tender Fruit", "Kind Berry",
    
    -- Prehistoric Update Seeds
    "Dino Berry", "T-Rex Fruit", "Raptor Berry", "Mammoth Fruit", "Saber Tooth Berry", "Cave Berry", "Stone Fruit", "Fossil Berry",
    "Ancient Fruit", "Primitive Berry", "Prehistoric Peach", "Jurassic Berry", "Triassic Fruit", "Cretaceous Berry", "Paleozoic Fruit"
}

-- Add all seeds to the Seeds content frame
for _, seedName in ipairs(seedsList) do
    local scriptCode = string.format([[
        while true do
            local args = {[1] = "%s"}
            local success, err = pcall(function()
                game:GetService("ReplicatedStorage").GameEvents.BuySeedStock:FireServer(unpack(args))
            end)
            if not success then
                warn("Failed to buy %s: " .. tostring(err))
            end
            wait(0.1) -- Small delay to prevent spam
        end
    ]], seedName, seedName)
    
    createToggleItem(SeedContentFrame, seedName, scriptCode)
end

-- Gear List - All available gear in Grow a Garden
local gearList = {
    "Watering Can", "Trowel", "Shovel", "Axe", "Pickaxe", "Fishing Rod", "Net", "Shears", "Gloves", "Boots",
    "Hat", "Shirt", "Pants", "Backpack", "Lantern", "Compass", "Map", "Binoculars", "Camera", "Radio",
    "Sprinkler", "Advanced Sprinkler", "Godly Sprinkler", "Master Sprinkler", "Lightning Rod", "Harvest Tool",
    "Friendship Pot", "Cleaning Spray", "Favorite Tool", "Mutation Spray", "Stalk Sprout Sprinkler", "Tropical Mist Sprinkler"
}

-- Add all gear to the Gear content frame
for _, gearName in ipairs(gearList) do
    local scriptCode = string.format([[
        while true do
            local args = {[1] = "%s"}
            local success, err = pcall(function()
                game:GetService("ReplicatedStorage").GameEvents.BuyGearStock:FireServer(unpack(args))
            end)
            if not success then
                warn("Failed to buy %s: " .. tostring(err))
            end
            wait(0.1) -- Small delay to prevent spam
        end
    ]], gearName, gearName)
    
    createToggleItem(GearContentFrame, gearName, scriptCode)
end

-- Pet List - All available eggs in Grow a Garden
local eggList = {
    "Common Egg", "Uncommon Egg", "Rare Egg", "Legendary Egg", "Mythical Egg", "Divine Egg",
    "Common Summer Egg", "Rare Summer Egg", "Exotic Egg", "Dinosaur Egg", "Primal Egg", "Zen Egg",
    "Bee Egg", "Bug Egg", "Paradise Egg", "Rainbow Egg", "Golden Egg", "Silver Egg", "Crystal Egg",
    "Diamond Egg", "Ruby Egg", "Emerald Egg", "Sapphire Egg", "Topaz Egg", "Amethyst Egg", "Opal Egg",
    "Platinum Egg", "Titanium Egg", "Copper Egg", "Bronze Egg", "Iron Egg", "Ancient Egg", "Fossil Egg"
}

-- Add all eggs to the Pet content frame
for _, eggName in ipairs(eggList) do
    local scriptCode = string.format([[
        while true do
            local args = {[1] = "%s"}
            local success, err = pcall(function()
                game:GetService("ReplicatedStorage").GameEvents.BuyEggStock:FireServer(unpack(args))
            end)
            if not success then
                warn("Failed to buy %s: " .. tostring(err))
            end
            wait(0.1) -- Small delay to prevent spam
        end
    ]], eggName, eggName)
    
    createToggleItem(PetContentFrame, eggName, scriptCode)
end

-- Make the UI visible
ScreenGui.Enabled = true


